### ISSUE TITLE
Delete notification signal when choosing "(o) open"

### ISSUE THREAD

**Issue by wschlich** [daskeyboard/daskeyboard-applet--github#1]
It doesn't make any sense at all having to delete a notification "(#)" after opening them in the browser "(o)", just unnecessary hassle.

**Comment by InnovativeInventor** [comment]
@wschlich I totally agree. I've opened up a [pull request](#2) to change the polling interval to 15 seconds (from 5 minutes), so the keyboard will update faster after you mark the notification as read. 

Here is a question I posed in the pull request: can we add a button that marks everything as read and refreshes the keyboard?

@fabiendv please look at the [pull request](#2)

**Comment by InnovativeInventor** [comment]
@wschlich The pull request was merged (the polling interval is now much shorter). This should hopefully make life better for GitHub applet users.
