### ISSUE TITLE
Provide option for notification setting

### ISSUE THREAD

**Issue by crstauf** [daskeyboard/daskeyboard-applet--github#4]
There is no option for the applet's notification setting: in my case, I'd like the key to change color, rather than pulse.

**Comment by crstauf** [comment]
@InnovativeInventor Is this possible?

**Comment by InnovativeInventor** [comment]
@crstauf Yes, I believe it is:

https://github.com/daskeyboard/daskeyboard-applet--github/blob/master/index.js#L123

If you change blink to any one of these options, you can probably achieve the desired effect:
![image](https://user-images.githubusercontent.com/20117409/88462200-938ad200-ce77-11ea-9dfc-e4c1204a372f.png)
(Source: https://www.daskeyboard.io/api-resources/signal/create-signal/)

PS: I'm not a maintainer of this repo nor do I work at Das Keyboard (just a customer who happens to be a developer)

**Comment by crstauf** [comment]
> I'm not a maintainer of the repo nor do I work at Das Keyboard

@InnovativeInventor My apologies. Do you know whom I should tag to request a configuration option for the notification type?

**Comment by InnovativeInventor** [comment]
@crstauf I believe @Mubramaj was the one who merged my PR. I'm not sure how responsive Das Keyboard will be to such a feature request, but it should be fairly simple for you to change yourself.

Just change [this](https://github.com/daskeyboard/daskeyboard-applet--github/blob/master/index.js#L123):
```js
        return new q.Signal({
          points: [
            [new q.Point('#FF0000', q.Effects.BLINK)]
          ],
          name: 'GitHub',
          message: numberNotifications > 1 ? 'Unread notifications available.' : 'Unread notification available.',
          link: {
            url: 'https://www.github.com/notifications',
            label: 'Show on GitHub',
          }
        });
```
to this:
```js
        return new q.Signal({
          points: [
            [new q.Point('#FF0000', q.Effects.Set_COLOR)]
          ],
          name: 'GitHub',
          message: numberNotifications > 1 ? 'Unread notifications available.' : 'Unread notification available.',
          link: {
            url: 'https://www.github.com/notifications',
            label: 'Show on GitHub',
          }
        });
```

Should be fairly straightforward.

**Comment by crstauf** [comment]
@InnovativeInventor Thanks for the snippet!

Where can I find the applet code on my machine? A quick Google search didn't yield anything obvious.

**Comment by InnovativeInventor** [comment]
@crstauf Here is how you load a custom applet: https://www.daskeyboard.io/applet-development/

**Comment by crstauf** [comment]
Thanks for all your help, @InnovativeInventor; I'll try installing as a custom applet.

**Comment by crstauf** [comment]
Finally got around to trying this, and discovered that, apparently, oAuth applets are not yet supported in dev mode. 👎 

Will try hard-coding API access.

**Comment by crstauf** [comment]
Got it!

Steps:
1. Create a GitHub personal access token with `Notifications` scope.
2. Change the `getGithubAccessToken()` and `refreshGithubAccessToken()` functions to return the personal access token.
3. Change authorization type from `Bearer` to ~`Basic`~ `token` (in two places).
4. Change `q.Effects.BLINK` to `q.Effects.SET_COLOR`.

It'd be nice if this were an option in the applet to choose the effect type, so I'll leave this issue open, but these steps should work for anyone else.

Edit 2021-04-25: Change `Basic` to `token` due to GitHub API token changes.

**Comment by InnovativeInventor** [comment]
If you don't want the oauth workaround, you could always open up a pull request to this repo.

**Comment by crstauf** [comment]
> you could always open up a pull request to this repo.

Unfortunately I'm not familiar with this type of JavaScript, so have no idea how to setup a setting for effect type. If I did, I certainly would open a PR.

**Comment by Mubramaj** [comment]
Hi,

Perhaps it could be an option in the user `questions` configuration. 
A lot of applets already have this in place like https://github.com/daskeyboard/daskeyboard-applet--montastic

If a pull request is opened I will be happy to review it and merge it

**Comment by crstauf** [comment]
@Mubramaj Thanks so much for the direction! I have submitted PR. :smile:
